version: 2
updates:
  - package-ecosystem: "pip" # Python pip package manager
    directory: "/" # Root directory of your project
    schedule:
      interval: "weekly" # Check for updates on a weekly basis
